name: high_chart
description: A chart library based on High Charts (.JS), able to build advanced charts like Pie chart, linear chart, etc.
version: 1.0.0
homepage: https://github.com/senthilnasa/high_chart

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

  #Flutter Web View Plugin
  webview_flutter: ^1.0.7


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  plugin:
    platforms:
      android:
        package: me.senthil.high_chart
        pluginClass: HighChartPlugin
      ios:
        pluginClass: HighChartPlugin
